Universidade Federal do Rio Grande do Sul (UFRGS)   
Programa de Pós-Graduação em Engenharia Civil (PPGEC)   

# PEC00144: Experimental Methods in Civil Engineering


### Part I: Analysis
[2.   Dimensional analysis and similarity](#section_2)   
[2.1. Quantities, units, dimensions](#section_21)   
[2.2. Dataframe for scales computation](#section_22)   
[2.3. The Theorem of Pi's by Vaschy-Buckinghan](#section_23)   
[2.4. Change of base units](#section_24)  
[2.5. Change of units is like change of scale](#section_25)  
[2.6. Famous Pi-Numbers](#section_26)  

---
_Prof. Marcelo M. Rocha, Dr.techn._ [(ORCID)](https://orcid.org/0000-0001-5640-1020)  
_Porto Alegre, RS, Brazil_ 


In [14]:
# Importing Python modules required for this notebook
# (this cell must be executed with "shift+enter" before any other Python cell)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## 2. Dimensional analysis and similarity <a name="section_2"></a> 

### 2.1. Quantities, units, dimensions  <a name="section_21"></a> 

Prof. G.I. Barenblatt has written in his book _Dimensional Analysis_ (1987):   

>_In fact, the idea on which dimensional analysis is based is very simple, and can be 
understood by all: physical laws do not depend on arbitrariness in the choice of basic 
units of measurement. An important conclusion can be drawn from this simple idea 
using simple arguments: the functions that express physical laws must possess a 
certain fundamental property, which in mathematics is called generalized homogeneity 
or symmetry. This property allows the number of arguments in these functions to be 
reduced, thereby making it simpler to obtain them (by calculating them or determining 
them experimentally). This is, in fact, the entire content of dimensional analysis - there 
is nothing more to it._

In other words, the units resulting from both sides of an equation must be the same.
Although simple, this idea has allowed great scientists like Newton, Rayleigh, Maxwell, 
Reynolds, Kolmogorov, Cauchy, and many others, to proposed many fundamental 
physical principles.

To illustrate how the law of _dimensional homogeneity_ can be applied, let us 
investigate the free vibration frequency, $f_{\rm n}$, of an undamped mass-spring 
system with one degree of freedom.

<img src="resources/figSDOF.jpg" alt="figSDOF" width="360px"/>

The frequency $f_{\rm n}$ could be derived from mechanical principles like dynamic
equilibrium equations, but we take the alternative dimensional path instead.
The system above _may_ involve several physical quantities like: 

* the instantaneous position, $u$,   
* the oscillating mass, $m$,   
* the time, $t$,   
* the displacement amplitude, $u_0$,   
* the spring linear stiffness, $k$, and also   
* the free vibration frequency, $f_{\rm n}$.  

The completeness of this set of quantities is essential for the success of our
dimensional analysis. The analysis process requires an investigation of possible
relationships among the _candidate_ quantities above and the frequency $f_{\rm n}$. 
Let us take a look at their _units of measurement_: 

\begin{align*}
[ u ]        &= [L]^{1}[M]^{0}[T]^{0}  \\
[ m ]        &= [L]^{0}[M]^{1}[T]^{0}  \\
[ t ]        &= [L]^{0}[M]^{0}[T]^{1}  \\
[ u_0 ]      &= [L]^{1}[M]^{0}[T]^{0}  \\
[ k ]        &= [L]^{0}[M]^{1}[T]^{-2} \\
[ f_{\rm n}] &= [L]^{0}[M]^{0}[T]^{-1}
\end{align*}

where the brackets mean "units of". One can observe that all measurement units have been
written in terms of only three _fundamental units_: length, $[L]$, mass, $[M]$, and time, $[T]$. 
Most principles in solid mechanics and structural dynamics may be expressed with these 
three units only. Eventually the temperature, $\Theta$, may be also required.
For the sake of simplicity, hereafter brackets will be ommited.

The quantities directly subordinated to the fundamental units are called _fundamental
quantities_, which are the length, the mass and the time, while other units and quantities
are called _derived_ units and quantities, like stiffness, frequency, acceleration, etc. 
The dependency of derived units on the fundamental units are expressed through _dimensional 
formulae_, as shown above, which are always _power-law monomials_. The exponents applyed to the 
fundamental units in these formulae are called _dimensions_ or _dimension exponents_.

In the case of using the _International System_ (SI), the three fundamental units are the
meter (m), the kilogram (kg), and the second (s). In the example above this means that:

\begin{align*}
[ u ]        &= {\rm m}^{1}{\rm kg}^{0}{\rm s}^{0} = {\rm m}  \\
[ m ]        &= {\rm m}^{0}{\rm kg}^{1}{\rm s}^{0} = {\rm kg} \\
[ t ]        &= {\rm m}^{0}{\rm kg}^{0}{\rm s}^{1} = {\rm s}  \\
[ u_0 ]      &= {\rm m}^{1}{\rm kg}^{0}{\rm s}^{0} = {\rm m}  \\
[ k ]        &= {\rm m}^{0}{\rm kg}^{1}{\rm s}^{-2} = {\rm kg}/{\rm s}^{2} = {\rm N/m} \\
[ f_{\rm n}] &= {\rm m}^{0}{\rm kg}^{0}{\rm s}^{-1} = 1/{\rm s} = {\rm Hz}
\end{align*}

### 2.2. Dataframe for scales computation  <a name="section_22"></a> 

To facilitate the scales calculations as presented in this _notebook_, let us now import 
a ``pandas`` dataframe with physical quantities commonly used in engineering mechanics and
structural dynamics, aerodynamics, and fluid and soil mechanics:

In [15]:
DimData = pd.read_excel('resources/DimData.xlsx', sheet_name='DimData')

print(DimData)

                       descriptor   latex  L  M  T
a                    Acceleration       a  1  0 -2
α            Angular acceleration  \alpha  0  0 -2
ω               Angular frequency  \omega  0  0 -1
A                            Area       A  2  0  0
EI         Beam bending stiffness      EI  0  1 -2
GAs          Beam shear stiffness    GA_s  2  1 -2
ρ                         Density    \rho -3  1  0
μ               Dynamic viscosity     \mu -1  1 -1
F                           Force       F  1  1 -2
f                       frequency       f  0  0 -1
υ             Kinematic viscosity     \nu  2  0 -1
L                          Length       L  1  0  0
m                            Mass       m  0  1  0
im   Mass inertia per unit length     i_m  1  1  0
μA             Mass per unit area   \mu_A -2  1  0
μL           Mass per unit length   \mu_L -1  1  0
M                          Moment       M  2  1 -2
I               Moment of inertia       I  4  0  0
W               Resistent modul

Other quantities may be easily included in this dataframe by editing the Excel file
``DimData.xlsx``. Each entry in the table corresponds to a dimensional quantity, being the last
three columns the respective dimension exponents in the dimensional formulae.
Quantities like angles, strains, Poison's coefficient and ratio of critical damping are
by definition non-dimensional, so there is no need of including them in this table.
Relations between length measures, the so-called _form factors_, must also not be included.

Observe that, for the sake of clearness, we are using Unicode
variable names, like greek letters, which is a remarkable Python's feature.

To access the $LMT$ exponents of a set of quantities, let us say the ones selected for
the oscillator problem above, the dataframe ```loc``` view may be used:

In [16]:
par    = ['L', 'm', 't', 'L', 'k', 'f']   # selected dimensional quantities
LMT    = ['L', 'M', 'T']                  # three last columns of dataframe
DimMat = DimData.loc[par, LMT]            # the dimensional matrix

print(DimMat)

   L  M  T
L  1  0  0
m  0  1  0
t  0  0  1
L  1  0  0
k  0  1 -2
f  0  0 -1


According to ``pandas`` module, a subset of a dataframe is itself also a dataframe.
If only the dimension exponents are to be retrieved, the attribute ``values`` must be called,
returning a ``numpy`` 2D array.
This array will be required in the following sections, where we show how the information provided in the dataframe  ``DimData`` can be used to carry out units and scales changes for designing reduced scale models.

In [17]:
print(DimMat.values)

[[ 1  0  0]
 [ 0  1  0]
 [ 0  0  1]
 [ 1  0  0]
 [ 0  1 -2]
 [ 0  0 -1]]


Observe that the dataframe indices are the codes to access a specific quantity, 
while the following first column, which header is ``descriptor``, corresponds to a 
description to help identification. 
The dataframe also brings a column named ``latex`` with the $\LaTeX$ code for eventual automatic
plot labelling. 

### 2.3. The Vaschy-Buckingham's $\Pi$-Theorem  <a name="section_23"></a> 

The Vaschy-Buckingham's $\Pi$-Theorem may be expressed as follows:

>Let us assume that a given physical phenomenon involves $n$ _dimensional quantities_, denoted as $p_1, p_2, \dots, p_n$. For this phenomenon a mathematical model may be expressed as a general relation:<br><br>
\begin{equation}
 f\left (  p_1, p_2, \dots, p_n \right ) = 0 
\end{equation}<br>
>This relation may be replaced by another one with $r = n - k$ _non-dimensional quantities_:<br><br>
\begin{equation}
 F\left (  \Pi_1, \Pi_2, \dots, \Pi_r \right ) = 0
\end{equation}<br>
where $k$ is the number of fundamental units required to compose the units of all dimensional quantities involved. The $\Pi$-numbers have the general form:<br><br>
\begin{equation}
\Pi = p_1^{\alpha_1} \; p_2^{\alpha_2} \; \dots \; p_n^{\alpha_n}
\end{equation}<br>
where the exponents $\vec{\alpha} = \left [ \alpha_1 \; \alpha_2 \; \dots \; \alpha_n \right ]$ are such that the condition of non-dimensionality must always be fulfilled.

Recalling that in the present context the only required fundamental units are $L$, $M$, and $T$, 
then $k = 3$. A demonstration of this theorem can be found in the literatura and will not be
replicated here.

To apply this theorem, let us assemble a _dimensional matrix_, $\bf D$, with one column for
each fundamental unit and one row for each quantity involved in the analysis. The
dataframe ``DimMat`` defined in the previous section is an computational example of a 
dimensional matrix.  To build up $\Pi$-numbers we propose now some vector, $\vec{\alpha}$, 
such that (for $k = 3$):

\begin{equation}
\vec{\alpha}{\bf D} = \left[0 \hspace{5mm} 0 \hspace{5mm} 0 \right]
\end{equation}

There is no general rule for specifying $\vec{\alpha}$.
The practical principle that guides any proposition is some possible physical meaning.
If the dimensional analysis subject is not well known, relevant $\Pi$-numbers will
always result from some educated guess.
Even the choice of a relevant set of quantities is not always obvious, for it may
both exceed or lack completeness. 
At this point, one can clearly see that _dimensional analysis is not a panacea for 
model proposition_ and a good measure of experience, or even luck, may be required.

Going back to the oscillator problem, possible $\Pi$-numbers for the involved quantities are:

\begin{align*}
 \Pi_1 &= u^1 u_0^{-1} \\
 \Pi_2 &= t^1 \; f_{\rm n}^{1} \\
 \Pi_3 &= m^{-1/2} \; k^{1/2} \; f_{\rm n}^{-1} 
\end{align*}

where we can se that $\Pi_3$ is clearly the most interesting, with 

$$\vec{\alpha}_3 = \left [ 0 \;\; {-1/2} \;\;\; 0 \;\;\;  0 \;\; 1/2  \;\; {-1} \right]$$

The product $\vec{\alpha}_3{\bf D}$  evidentiates its non-dimensionality:

In [18]:
α3 = np.array([0, -1/2, 0, 0, 1/2, -1])

print(np.matmul(α3, DimMat))

[0. 0. 0.]


Representing physical phenomena as relationships among non-dimensional quantities 
certainly implies independence of the chosen units system, but it does not ensure 
independence of length scale, which is the holy grail of any mathematical model.
On the other hand, models may eventually include the length scale dependence itself 
whenever enough data is available. 

For the oscillator example above, it can be shown both experimentally or from physical 
principles, that $\Pi_3 = 2\pi$ for small $u_0$. This constant results is, within some 
limits, also (length) scale independent. 
The whole point here is that this result _can be experimentally obtained through dimensional
analysis of experimental outcomes even if the applicable principles of physics were
not known in advance_.
This justifies the importance of dimensional analsys, for it has allowed great cientists
to propose models with $\Pi$-numbers governing many important phenomena. Some remarkable
examples will be shown in section 2.6.


### 2.4. Change of base units  <a name="section_24"></a> 

As fórmulas dimensionais permitem que se recalculem as unidades derivadas a partir de uma nova escolha das unidades de base. Esse cálculo pode ser usado para diversas finalidades, como por exemplo: (1) mudanças no sistema de unidades, como por exemplo do SI para o sistema britânico, ou (2) mudanças de escala das grandezas, para projeto de modelos reduzidos.

A escolha das grandezas $L$, $M$, e $T$ como grandezas de base é de certa forma arbitrária, embora esteja bem estabelecida internacionalmente. Contudo, é possível substituir essas três grandezas e logo obter uma nova matriz dimensional para outras três grandezas derivadas.

Supondo o estudo de um fenômeno qualquer na base $LMT$, no qual se deseje utilizar uma nova base composta pelas grandezas $A$, $B$ e $C$. A matriz dimensional da nova base é: 

\begin{align*}
 A &= L^{a_{L}} M^{a_{M}} T^{a_{T}} \\
 B &= L^{b_{L}} M^{b_{M}} T^{b_{T}} \\
 C &= L^{c_{L}} M^{c_{M}} T^{c_{T}}
\end{align*}

As an example, let us propose a new base by selecting three quantities from the dataframe
```DimData```. For instance, let us take $A = L$ (length),  $B = \rho$ (density), and $C = a$ (acceleration):

In [26]:
ABC  = ['L', 'ρ', 'a']
base = DimData.loc[ABC, LMT]

print(base)

   L  M  T
L  1  0  0
ρ -3  1  0
a  1  0 -2


The new base must include quantities with linearly independent dimensions! It is not possible,
for instance, to choose length, area and volume, for their dimensions are multiples
one of each other.

Now we take logarithms from both sides of the equation above:

\begin{align*}
\log A &= \log \left ( L^{a_{L}} M^{a_{M}} T^{a_{T}} \right ) = a_{L}\log L + a_{M}\log M + a_{T}\log T \\
\log B &= \log \left ( L^{b_{L}} M^{b_{M}} T^{b_{T}} \right ) = b_{L}\log L + b_{M}\log M + b_{T}\log T \\
\log C &= \log \left ( L^{c_{L}} M^{c_{M}} T^{c_{T}} \right ) = c_{L}\log L + c_{M}\log M + c_{T}\log T
\end{align*}

In matrix notation:
\begin{equation}
\left [ \begin{array}{ccc}
         a_{L}& a_{M}& a_{T} \\
         b_{L}& b_{M}& b_{T} \\
         c_{L}& c_{M}& c_{T}
        \end{array} \right ]
\left [ \begin{array}{ccc}
        \log L \\
        \log M \\
        \log T
        \end{array} \right ] =
\left [ \begin{array}{ccc}
        \log A \\
        \log B \\
        \log C
        \end{array} \right ]
\end{equation}

where it can be observed that the the right hand side is the dimension matrix for the
new base. By isolating the vector with the base quantities it gives:
onde se observa que a matriz do lado esquerdo da equação é a matriz dimensional da nova base. 

\begin{equation}
\left [ \begin{array}{ccc}
        \log L \\
        \log M \\
        \log T
        \end{array} \right ] =
\left [ \begin{array}{ccc}
         a_{A}& a_{B}& a_{C} \\
         b_{A}& b_{B}& b_{C} \\
         c_{A}& c_{B}& c_{C}
        \end{array} \right ]
\left [ \begin{array}{ccc}
        \log A \\
        \log B \\
        \log C
        \end{array} \right ]
\end{equation}

where:

\begin{equation}
\left [ \begin{array}{ccc}
      a_{A}& a_{B}& a_{C} \\
      b_{A}& b_{B}& b_{C} \\
      c_{A}& c_{B}& c_{C}
     \end{array} \right ] =
\left [ \begin{array}{ccc}
      a_{L}& a_{M}& a_{T} \\
      b_{L}& b_{M}& b_{T} \\
      c_{L}& c_{M}& c_{T}
     \end{array} \right ] ^{-1}
\end{equation}

And now it becomes clear why the quantities in the new base must have linearly independent
dimensions, otherwise the dimension matrix cannot be inverted.
Going back to the monomial form we get:

\begin{align*}
 L &= A^{a_{A}} B^{a_{B}} C^{a_{C}} \\
 M &= A^{b_{A}} B^{b_{B}} C^{b_{C}} \\
 T &= A^{c_{A}} B^{c_{B}} C^{c_{C}}
\end{align*}

Portanto, que para se obter a matriz dimensional das grandezas fundamentais em uma nova base basta inverter a matriz dimensional (transposta) desta nova base. Isso só é possível se essa matriz tem determinante positivo, ou seja, as grandezas que constituem a nova base devem ter expoentes de dimensão linearmente independentes entre si. Isso significa, por exemplo, que não se poderia escolher como novas grandezas de base a _velocidade_ (m/s), o _comprimento_ (m), e o _tempo_ (s), pois as unidades de uma das três grandezas pode se representada por uma relação entre as outras duas. Logo, a matriz dimensional não poderia ser invertida.

A inversão da matriz dimensional da nova base é feita em Python pelo módulo ```numpy``` como:

In [27]:
i_base = np.linalg.inv(base)

print(i_base)

[[ 1.  -0.  -0. ]
 [ 3.   1.   0. ]
 [ 0.5 -0.  -0.5]]


Vejamos agora o que acontece com uma grandeza derivada, $X$, para a qual se deseje conhecer as dimensões na nova base. As dimensões na base $LMT$ são dadas por:

\begin{equation}
 X = L^{\alpha_{L}} M^{\beta_{M}} T^{\gamma_{T}}
\end{equation} 

e portanto:

\begin{equation}
 X = \left ( A^{a_{A}} B^{a_{B}} C^{a_{C}} \right )^{\alpha_{L}}
     \left ( A^{b_{A}} B^{b_{B}} C^{b_{C}} \right )^{\beta_{M}}
     \left ( A^{c_{A}} B^{c_{B}} C^{c_{C}} \right )^{\gamma_{T}} 
\end{equation}

Rearranjando-se os termos:

\begin{equation}
 X = A^{(a_{A}\alpha_{L} + b_{A}\beta_{M} + c_{A}\gamma_{T})}
     B^{(a_{B}\alpha_{L} + b_{B}\beta_{M} + c_{B}\gamma_{T})}
     C^{(a_{C}\alpha_{L} + b_{C}\beta_{M} + c_{C}\gamma_{T})}
   = A^{\alpha_{A}} B^{\beta_{B}} C^{\gamma_{C}}
\end{equation}

Observa-se que as dimensões na nova base podem ser calculadas com uma multiplicação matricial:

\begin{equation}
\left [ \begin{array}{ccc}
        \alpha_{A} \\
        \beta_{B} \\
        \gamma_{C}
        \end{array} \right ]  =
\left [ \begin{array}{ccc}
         a_{A}& a_{B}& a_{C} \\
         b_{A}& b_{B}& b_{C} \\
         c_{A}& c_{B}& c_{C}
        \end{array} \right ] ^{T} 
\left [ \begin{array}{ccc}
        \alpha_{L} \\
        \beta_{M} \\
        \gamma_{T}
        \end{array} \right ] 
\end{equation}

Com o módulo ```numpy``` essa multiplicação é feita da seguinte forma:

In [29]:
NewMat = pd.DataFrame(data    = np.matmul(DimMat,i_base),
                      index   = DimMat.index,
                      columns = ABC)
print(NewMat)

     L    ρ    a
L  1.0  0.0  0.0
m  3.0  1.0  0.0
t  0.5  0.0 -0.5
L  1.0  0.0  0.0
k  2.0  1.0  1.0
f -0.5  0.0  0.5


This new dimension matrix contains the dimensions of the selected quantities for the new base.
These dimensions can be used for changing the unit system in the much same way it can be used
for changing scales.

### 2.5. Changing units is like changing scales <a name="section_25"></a> 

Como já mencionado, uma das aplicações da mudança de base é a mudança de unidades das grandezas fundamentais. A nova matriz dimensional nos permite calcular o efeito desta mudança nas grandezas derivadas. Por exemplo, vamos admitir que desejamos utilizar a milha nautica ao invés do metro como unidade de comprimento, e a hora ao invés do segundo como unidade do tempo. Vejamos como isso repercute na unidade de velocidade, sendo que a fórmula de cálculo é a mesma que foi anteriormente utilizada para a dimensão:

\begin{equation}
 X = A^{\alpha_{A}} B^{\beta_{B}} C^{\gamma_{C}}
\end{equation}

For instance, let us take a change from meters per second (m/s) to knots (nautical miles per hour).
The units for the fundamental quantities are:


In [30]:
λ_L    =  1852/1                   # 1852 meters is 1 nautical mile
λ_m    =  1/1                      # mass does not matter for velocity
λ_t    =  3600/1                   # 3600 seconds is 1 hour

scales =  np.tile([λ_L, λ_m, λ_t],(1,1))


Now we get the dimensions of velocity and apply the equation:

In [25]:
Dim_v  = DimData.loc[['v'], LMT]      # dimensions of velocity in the LMT base
λ_v    = np.prod(scales**Dim_v, axis=1);

print('Velocity in knots is {0:5.3f}m/s.'.format(λ_v[0]))

Velocity in knots is 0.514m/s.


what means that 1m/s corresponds to approximately 1.94knots.

Outro aspecto interessante desse cálculo é que exatamente o mesmo procedimento pode ser utilizado para se modificar a escala de alguns parâmetros que descrevem um fenômeno físico, e conhecer a repercussão desta mudança em outros parâmetros relevantes. Esta é a ferramenta básica utilizada no projeto de modelos reduzidos, que será discutido na próxima seção.

Por exemplo, abaixo está o cálculo da nova escala de velocidade para uma mudança na escala de comprimento, $L$,  mantendo-se a escala de massa específica, $\rho$, e da aceleração da gravidade, $g$ inalteradas:

In [71]:
ABC    = ['L', 'ρ', 'a']
base   = DimData.loc[ABC, LMT].values
i_base = np.linalg.inv(base)

λ_L    =  1/160                 # length scale for the reduced model
λ_ρ    =  1/1                   # density remains unchanged (same material)
λ_a    =  1/1                   # acceleration remains unchanged (same gravity)

scales =  np.tile([λ_L, λ_ρ, λ_a],(1,1))

Now we change base, calculate new dimensions and apply scales:

In [73]:
Dim_v  = DimData.loc[['v'],LMT]   # dimensions of velocity in the LMT base

New_v  = pd.DataFrame(data    = np.dot(Dim_v, i_base),
                      index   = Dim_v.index,
                      columns = ABC)

λ_v    = np.prod(scales**New_v, axis=1);

print('Velocity in the new scale is {0:6.4f} times the full scale velocity.'.format(λ_v[0]))

Velocity in the new scale is 0.0791 times the full scale velocity.


This means, for instance, that a wind speed of 1m/s applied over the model corresponds to a
wind speed of 12.65m/s applied over the original structure (also called the _prototype scale_),
as long as all other scales are equally observed for the model construction.
 

### 2.6. Famous $\Pi$-numbers  <a name="section_26"></a> 

A análise dimensional permitiu que grandes cientistas apresentassem ao mundo números adimensionais que regem fenômenos importantes, tais como o número de Reynolds (forças de arrasto em corpos imersos em fluidos), de Froude (relação entre forças gravitacionais e inerciais), ou de Strouhal (frequência de desprendimento de vórtices alternados). 

#### _Reynold's Number_

Um dos exemplos mais citados sobre uso de adimensionais para descrever fenômenos físicos é a relação entre o coeficiente de arrasto e o número de Reynolds no estudo do escoamento de fluidos em torno de corpos sólidos. O coeficiente de arrasto, $C_{\rm D}$, é uma relação entre a força de arrasto, $F_{\rm D}$ é a força aerodinâmica, $\rho V^2 A/2$, onde $\rho$ é a massa específica do fluido, $V$ é a velocidade do escoamento, e $A$ é a área exposta de referência (geralmente a seção perpendicular ao escoamento):

$$ C_{\rm D} = \frac{F_{\rm D}}{\frac{1}{2} \rho V^2 A}$$

Já o número de Reynolds representa uma relação entre as forças inerciais e as forças de viscosidade em um fluido, definido como:

$$ {\rm Re} = \frac{V \, D}{\nu}$$ 

onde $D$ é uma dimensão de referência da área exposta (perpendicular à direção do escoamento), e $\nu$ é a viscosidade cinemática do fluido ($\nu \approx 1.48 \times 10^5 {\rm m^2/s}$ para o ar na temperatura ambiente). A figura abaixo mostra o que resulta de uma investigação experimental da relação entre estes dois adimensionais para uma esfera.

<img src="resources/drag_coefficient.jpg" alt="drag_coefficient" width="600px"/>

Observa-se, neste caso, que a relação apresentada graficamente pode ser usada em qualquer escala, independentemente de existirem modelos preditivos baseados em princípios físicos. Aqui o fenômeno é descrito apenas em termos de adimensionais.
